### ISSUE TITLE
Make tabs uniform

### ISSUE THREAD

**Issue by ben432rew** [erikasland/RubyBank#9]
There are some spaces, some tabs in the files.  Make it uniform across all files.

**Comment by ben432rew** [comment]
Check ruby conventions to see if it's preferred to use hard or soft tabs.  I use soft tabs, most python people do soft tabs.

**Comment by em77** [comment]
According to the Ruby Style Guide and a number of other sources, the way to go is soft tabs with each tab being 2 spaces. I'm converting all files to this format now.

https://github.com/bbatsov/ruby-style-guide#spaces-indentation
